language: cpp
compiler:
    - gcc

notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - upi.bhalla@gmail.com

        on_success: change
        on_failure: always

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libopenscenegraph-dev
    - sudo apt-get install -y libqt4-dev
    - sudo apt-get install -y libqt4-opengl-dev
    - sudo apt-get install -y python-qt4-gl
    - sudo apt-get install -y python-qt4-dev
    - sudo apt-get install -y python-sip-dev
    - sudo apt-get install -y python-numpy
    - sudo apt-get install -y python-matplotlib cmake g++
    - sudo pip install pymoose 
    - sudo pip install numpy --upgrade 

script: 
    - ./.travis_build.sh
